version: '3.9'

services:
  backend:
    build:
      context: ./backend
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      NODE_ENV: development
      PASSWORD: password
    ports:
      - "8080:8080"
